# Generated by Django 5.2.7 on 2025-11-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_servicios',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='id_clientes',
            field=models.IntegerField(default=1),
        ),
    ]
